import { Job, Company, Candidate, Application } from './types';

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'c1',
    name: 'Shopify',
    slug: 'shopify',
    legalName: 'Shopify Inc.',
    sector: 'Tech',
    industry: 'E-commerce',
    size: '10001+',
    canadianHQ: true,
    hqCity: 'Ottawa',
    hqProvince: 'ON',
    exactAddress: '150 Elgin St, Ottawa, ON K2P 1L4, Canada',
    website: 'https://shopify.com',
    description: 'A leading global commerce company providing trusted tools to start, grow, market, and manage a retail business of any size.',
    isPubliclyTraded: true,
    stockTicker: 'TSX:SHOP',
    knownATSPortal: 'lever',
    techStack: ['Ruby on Rails', 'React', 'GraphQL', 'Go'],
    confidenceScore: 98,
    needsManualReview: false,
    enrichedAt: new Date().toISOString()
  },
  {
    id: 'c2',
    name: 'Royal Bank of Canada',
    slug: 'royal-bank-of-canada',
    legalName: 'Royal Bank of Canada',
    sector: 'Finance',
    industry: 'Banking',
    size: '10001+',
    canadianHQ: true,
    hqCity: 'Toronto',
    hqProvince: 'ON',
    exactAddress: '200 Bay St., Toronto, ON M5J 2J5, Canada',
    website: 'https://rbc.com',
    description: 'One of Canada\'s largest banks and one of the largest banks in the world, based on market capitalization.',
    isPubliclyTraded: true,
    stockTicker: 'TSX:RY',
    knownATSPortal: 'workday',
    techStack: ['Java', 'Spring Boot', 'Angular', 'Python'],
    confidenceScore: 99,
    needsManualReview: false,
    enrichedAt: new Date().toISOString()
  },
  {
    id: 'c3',
    name: 'CGI',
    slug: 'cgi',
    legalName: 'CGI Inc.',
    sector: 'Consulting',
    industry: 'IT Services',
    size: '10001+',
    canadianHQ: true,
    hqCity: 'Montreal',
    hqProvince: 'QC',
    exactAddress: '1350 René-Lévesque Blvd W, Montreal, QC H3G 1T4, Canada',
    website: 'https://cgi.com',
    description: 'Among the largest IT and business consulting services firms in the world.',
    isPubliclyTraded: true,
    stockTicker: 'TSX:GIB.A',
    knownATSPortal: 'taleo',
    techStack: ['C#', '.NET', 'Java', 'Azure'],
    confidenceScore: 95,
    needsManualReview: false,
    enrichedAt: new Date().toISOString()
  },
  {
    id: 'c4',
    name: 'Inetum',
    slug: 'inetum',
    legalName: 'Inetum S.A.',
    sector: 'Consulting',
    industry: 'IT Services',
    size: '10001+',
    canadianHQ: false,
    hqCity: 'Paris',
    hqProvince: null as any,
    exactAddress: '145 Boulevard Victor Hugo, 93400 Saint-Ouen-sur-Seine, France',
    website: 'https://inetum.com',
    description: 'Agile IT services company providing digital services and solutions.',
    isPubliclyTraded: false,
    knownATSPortal: 'smartrecruiters',
    techStack: ['Java', 'React', 'AWS'],
    confidenceScore: 55, // Low confidence to show warning
    needsManualReview: true,
    enrichedAt: new Date().toISOString()
  },
  {
    id: 'c5',
    name: 'OpenText',
    slug: 'opentext',
    legalName: 'Open Text Corporation',
    sector: 'Tech',
    industry: 'Enterprise Software',
    size: '10001+',
    canadianHQ: true,
    hqCity: 'Waterloo',
    hqProvince: 'ON',
    exactAddress: '275 Frank Tompa Dr, Waterloo, ON N2L 0A1, Canada',
    website: 'https://opentext.com',
    description: 'Develops and sells enterprise information management software.',
    isPubliclyTraded: true,
    stockTicker: 'TSX:OTEX',
    knownATSPortal: 'successfactors',
    techStack: ['Java', 'C++', 'JavaScript', 'Kubernetes'],
    confidenceScore: 96,
    needsManualReview: false,
    enrichedAt: new Date().toISOString()
  },
  {
    id: 'c6',
    name: 'Wealthsimple',
    slug: 'wealthsimple',
    legalName: 'Wealthsimple Inc.',
    sector: 'Finance',
    industry: 'Fintech',
    size: '1001-5000',
    canadianHQ: true,
    hqCity: 'Toronto',
    hqProvince: 'ON',
    exactAddress: '80 Spadina Ave., Suite 400, Toronto, ON M5V 2J4, Canada',
    website: 'https://wealthsimple.com',
    description: 'Online investment management service focused on millennials.',
    isPubliclyTraded: false,
    knownATSPortal: 'greenhouse',
    techStack: ['Ruby', 'TypeScript', 'React Native', 'AWS'],
    confidenceScore: 92,
    needsManualReview: false,
    enrichedAt: new Date().toISOString()
  },
  {
    id: 'c7',
    name: 'Confidential Company',
    slug: 'confidential',
    legalName: undefined,
    sector: 'Unknown',
    industry: 'Unknown',
    size: 'Unknown',
    canadianHQ: undefined,
    exactAddress: 'Confidential Location',
    description: 'This company has chosen to remain anonymous in their job posting.',
    confidenceScore: 0,
    needsManualReview: false,
    enrichedAt: new Date().toISOString(),
    enrichmentStatus: 'scraped'
  },
  {
    id: 'c8',
    name: 'Quantum Data Corp',
    slug: 'quantum-data-corp',
    enrichmentStatus: 'pending'
  },
  {
    id: 'c9',
    name: 'NorthStar Logistics',
    slug: 'northstar-logistics',
    enrichmentStatus: 'pending'
  }
];

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: 'can1',
    name: 'Alice Johnson',
    role: 'Frontend Developer',
    email: 'alice@example.com',
    phone: '+1 (613) 555-0123',
    location: 'Ottawa, ON',
    linkedinUrl: 'https://linkedin.com/in/alicejohnson',
    resumeUrl: 'https://example.com/resumes/alice.pdf',
    yearsOfExperience: 5,
    skills: ['React', 'TypeScript', 'Tailwind'],
    status: 'Interviewing',
    bio: 'Experienced frontend engineer with a focus on React and modern CSS frameworks.'
  },
  {
    id: 'can2',
    name: 'Bob Smith',
    role: 'Data Scientist',
    email: 'bob@example.com',
    phone: '+1 (416) 555-0199',
    location: 'Toronto, ON',
    linkedinUrl: 'https://linkedin.com/in/bobsmith',
    yearsOfExperience: 3,
    skills: ['Python', 'SQL', 'Machine Learning'],
    status: 'Available',
    bio: 'Data scientist passionate about extracting insights from complex datasets.'
  }
];

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Engineer',
    companyId: 'c1',
    companyName: 'Shopify',
    source: 'linkedin',
    url: 'https://linkedin.com/jobs/1',
    location: 'Remote, Canada',
    category: 'Engineering',
    isFavorite: true,
    applicationType: 'Easy Apply',
    requiredSkills: ['React', 'TypeScript', 'GraphQL'],
    status: 'Applied',
    appliedDate: '2024-03-15',
    isEasyApply: true,
    country: 'CA'
  },
  {
    id: '2',
    title: 'Full Stack Developer',
    companyId: 'c2',
    companyName: 'Royal Bank of Canada',
    source: 'indeed',
    url: 'https://indeed.com/jobs/2',
    location: 'Toronto, ON',
    category: 'Engineering',
    isFavorite: false,
    applicationType: 'External',
    requiredSkills: ['Java', 'Spring Boot', 'React'],
    status: 'Saved',
    isEasyApply: false,
    country: 'CA'
  },
  {
    id: '3',
    title: 'Cloud Architect',
    companyId: 'c3',
    companyName: 'CGI',
    source: 'linkedin',
    url: 'https://linkedin.com/jobs/3',
    location: 'Montreal, QC',
    category: 'Infrastructure',
    isFavorite: false,
    applicationType: 'External',
    requiredSkills: ['Azure', 'C#', 'Architecture'],
    status: 'Saved',
    isEasyApply: false,
    country: 'CA'
  },
  {
    id: '4',
    title: 'Software Engineer, Backend',
    companyId: 'c6',
    companyName: 'Wealthsimple',
    source: 'linkedin',
    url: 'https://linkedin.com/jobs/4',
    location: 'Toronto, ON',
    category: 'Engineering',
    isFavorite: true,
    applicationType: 'Easy Apply',
    requiredSkills: ['Ruby', 'PostgreSQL', 'AWS'],
    status: 'Interview',
    appliedDate: '2024-03-20',
    isEasyApply: true,
    country: 'CA'
  },
  {
    id: '5',
    title: 'Data Engineer',
    companyId: 'c5',
    companyName: 'OpenText',
    source: 'indeed',
    url: 'https://indeed.com/jobs/5',
    location: 'Waterloo, ON',
    category: 'Data',
    isFavorite: false,
    applicationType: 'External',
    requiredSkills: ['Python', 'Spark', 'Hadoop'],
    status: 'Saved',
    isEasyApply: false,
    country: 'CA'
  },
  {
    id: '6',
    title: 'React Native Developer',
    companyId: 'c7',
    companyName: 'Confidential Company',
    source: 'linkedin',
    url: 'https://linkedin.com/jobs/6',
    location: 'Vancouver, BC',
    category: 'Mobile',
    isFavorite: false,
    applicationType: 'Easy Apply',
    requiredSkills: ['React Native', 'iOS', 'Android'],
    status: 'Saved',
    isEasyApply: true,
    country: 'CA'
  },
  {
    id: '7',
    title: 'DevOps Engineer',
    companyId: 'c4',
    companyName: 'Inetum',
    source: 'linkedin',
    url: 'https://linkedin.com/jobs/7',
    location: 'Calgary, AB',
    category: 'Infrastructure',
    isFavorite: false,
    applicationType: 'External',
    requiredSkills: ['Kubernetes', 'Terraform', 'CI/CD'],
    status: 'Saved',
    isEasyApply: false,
    country: 'CA'
  },
  {
    id: '8',
    title: 'Machine Learning Engineer',
    companyId: 'c8',
    companyName: 'Quantum Data Corp',
    source: 'linkedin',
    url: 'https://linkedin.com/jobs/8',
    location: 'Vancouver, BC',
    category: 'Data Science',
    isFavorite: false,
    applicationType: 'Easy Apply',
    requiredSkills: ['Python', 'TensorFlow', 'PyTorch'],
    status: 'Saved',
    isEasyApply: true,
    country: 'CA'
  },
  {
    id: '9',
    title: 'Logistics Coordinator',
    companyId: 'c9',
    companyName: 'NorthStar Logistics',
    source: 'indeed',
    url: 'https://indeed.com/jobs/9',
    location: 'Calgary, AB',
    category: 'Operations',
    isFavorite: false,
    applicationType: 'External',
    requiredSkills: ['Supply Chain', 'Logistics', 'Excel'],
    status: 'Saved',
    isEasyApply: false,
    country: 'CA'
  }
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 'app1',
    jobId: '1',
    candidateId: 'can1',
    status: 'Interview',
    appliedDate: '2024-03-15',
    notes: 'Alice is a great fit for their Hydrogen team.'
  }
];
